version: "3.7"
services:
  main:
    container_name: georg-tsl8
    build:
      context: .
      dockerfile: "Dockerfile"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: ${GPU_COUNT:-all}
              capabilities: [ gpu ]
    # ports:
    #   - "8888:8888"
    #   - "9999:9999"
    shm_size: "128gb"
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - "${HOST_APP_FOLDER:-~/Desktop/tsl8}:/app"
      - "/data:/data"
